// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3WAUDKAoMx74nqwALPhCZ0jGeG1g-f3c',
    appId: '1:992552615463:web:cc5531caea5402c2179802',
    messagingSenderId: '992552615463',
    projectId: 'device-streaming-84470d6b',
    authDomain: 'device-streaming-84470d6b.firebaseapp.com',
    storageBucket: 'device-streaming-84470d6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgk1Cft1CHHYxGQn8MmLQrNJnNkfifDFU',
    appId: '1:992552615463:android:97a30a735fdb3022179802',
    messagingSenderId: '992552615463',
    projectId: 'device-streaming-84470d6b',
    storageBucket: 'device-streaming-84470d6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-I0mqmoiqO2xlcMhpYfnwqnXrUOwESh0',
    appId: '1:992552615463:ios:40d82d0c84c66429179802',
    messagingSenderId: '992552615463',
    projectId: 'device-streaming-84470d6b',
    storageBucket: 'device-streaming-84470d6b.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-I0mqmoiqO2xlcMhpYfnwqnXrUOwESh0',
    appId: '1:992552615463:ios:40d82d0c84c66429179802',
    messagingSenderId: '992552615463',
    projectId: 'device-streaming-84470d6b',
    storageBucket: 'device-streaming-84470d6b.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3WAUDKAoMx74nqwALPhCZ0jGeG1g-f3c',
    appId: '1:992552615463:web:3fcdddf350e090c8179802',
    messagingSenderId: '992552615463',
    projectId: 'device-streaming-84470d6b',
    authDomain: 'device-streaming-84470d6b.firebaseapp.com',
    storageBucket: 'device-streaming-84470d6b.firebasestorage.app',
  );
}
